#config/settings.py
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700

WINDOW_TITLE = "Ant Colony"

FPS = 60

BACKGROUND_COLOR = (0, 0, 0)

CLICK_RADIUS = 50

# Colony
STARTING_ANTS = 10


# Ant
ANT_RADIUS = 10
ANT_SENSE_RADIUS = 15
ANT_MIN_SPEED = 0.5
ANT_MAX_SPEED = 1.0
ANT_TURN_SPEED = 2.0
ANT_DRAW_SIZE = 10

# Food
FOOD_RADIUS = 10
FOOD_DECAY_TIME = 5000

# Entity discovery
ANT_DISCOVERABLE_RADIUS = 10
FOOD_DISCOVERABLE_RADIUS = 30
NEST_DISCOVERABLE_RADIUS = 100

# Ant senses
ANT_SENSE_RADIUS = 50